version: '3.8'
services:
  financial_dashboard:
    container_name: financial_dashboard
    restart: always
    env_file: .env
    build: .
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d    
    depends_on: 
      - financial_dashboard  